FROM python:3.9-slim

WORKDIR /app

COPY req_for_docker/req_streamlit.txt /app/requirements.txt

RUN pip install --no-cache-dir -r /app/requirements.txt

COPY . /app

EXPOSE 8501

CMD ["streamlit", "run", "Interface/app.py", "--server.enableCORS=false", "--server.address=0.0.0.0"]